version: '3'

services:
    sage:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: coppersmith
        volumes:
            - ./src:/home/sage/project
        container_name: coppersmith
        command: ["/home/sage/project/main.sage", "-m", "6", "-s", "250", "-d", "0.035"]
